---
abstract: 'Basic HTTP Auth Helper Plus'
author:
  - 'Brad Robertson <blr@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-BasicAuthPlus
no_index:
  directory:
    - t
    - inc
requires:
  Authen::Simple::LDAP: 0
  Authen::Simple::Passwd: 0
  Authen::Simple::Password: 0
  Mojolicious: 1.4
  Test::More: 0
version: 0.02
